### ISSUE TITLE
Add overview for leases without events

### ISSUE THREAD

**Issue by svenfinke** [awslabs/sandbox-accounts-for-events#10]
An overview for the users leases would come in handy if the event is running for multiple days - so that the customer does not have to enter the event ID over and over again - or if you created a lease without an event connection.

**Comment by moellr** [comment]
Interesting idea, I like it. Will add it to my feature request list for further improvements & add-ons.

**Comment by moellr** [comment]
Will not implement, this would extend the current scope of the project too far (trying to keep it lean)
