### ISSUE TITLE
Possibility of integrating Frontend logins with SSO?

### ISSUE THREAD

**Issue by varunchandak** [awslabs/sandbox-accounts-for-events#17]
Google or AWS Identity Center?

Can be beneficial for orgs having SSO enabled applications.

**Comment by moellr** [comment]
The frontend uses Amazon Cognito via AWS Amplify auth component, which is able to connect to other IDPs, so this should be achievable. Feel free to contribute to this repo when you have extended your setup, would be an interesting add-on.
