### ISSUE TITLE
How do we obtain CLI credentials like with vanilla DCE?

### ISSUE THREAD

**Issue by mmunem** [awslabs/sandbox-accounts-for-events#18]
e.g. in dce, the following cli command would reveal the cli credentials. I'm struggling to find out how to do the same using Sandbox Accounts for Events:

dce leases login --print-creds

(source: https://dce.readthedocs.io/en/latest/howto.html?highlight=credentials#logging-into-a-leased-account)

**Comment by moellr** [comment]
Sandbox Accounts for Events (SAfE) has been build for users that do not know how obtain or work with CLI credentials, so this functionality is not included. The easiest way to get credentials for your session would be to log into the AWS console via SAfE, open AWS CloudShell and run `aws sts get-session-token`. If you need to rely on vanilla DCE, you could also connect your local DCE CLI to the DCE backend in SAfE or deploy pure DCE only.
DCE is still a great tool in itself, it just lacks a user interface for non-developers (which might not be needed in your case).
