### ISSUE TITLE
Bucket cannot have ACLs set with ObjectOwnership's BucketOwnerEnforced setting

### ISSUE THREAD

**Issue by iprayforwaves** [awslabs/sandbox-accounts-for-events#29]
Cloudformation fails when trying to create LoggingBucket resource due to new AWS default bucket settings.

Error: Bucket cannot have ACLs set with ObjectOwnership's BucketOwnerEnforced setting (Service: Amazon S3;

Reference: https://docs.aws.amazon.com/AmazonS3/latest/userguide/about-object-ownership.html

**Comment by moellr** [comment]
Thx to [iprayforwaves](https://github.com/iprayforwaves) for fixing this, merged your pull request into main.
