### ISSUE TITLE
support for federated login

### ISSUE THREAD

**Issue by straav** [awslabs/sandbox-accounts-for-events#36]
adding support to use cognito's federated login would be amazing.

**Comment by straav** [comment]
Let me clarify we have Cognito working with federation and federation is creating users in the Cognito User Pool correctly but login is not working.
I have also altered the Authenticator function passing it the Social login providers, but login does not render it.

**Comment by moellr** [comment]
You will need to update/import the Amplify auth component to use federated login, as described here: https://docs.amplify.aws/lib/auth/social/q/platform/js/

**Comment by straav** [comment]
update is simple and builds fine, and Test Your Hosted UI Endpoint link works as expected. The issue is "login to existing account" does not bring up the federated login option to click through.

**Comment by moellr** [comment]
Got it. I have added your request to the "features to be considered" list, thx for the input.

**Comment by moellr** [comment]
Will not implement, this would extend the current scope of the project too far
