### ISSUE TITLE
Update of configuration values after deployment

### ISSUE THREAD

**Issue by SheVyY** [awslabs/sandbox-accounts-for-events#37]
I'd like to be able to update configuration values after the deployment is done. Is there a proper way on how to do that?

**For example:** 
I'd like to update **default-config-nuke-template.yml** after the deployment because I found out that there is 1 resource missing in that template and I need nuke to filter it. So far I destroyed the whole deployment, built it again with the new template, and deployed it again but this approach is not healthy as it's time-consuming and when everything is set I don't want to destroy everything just to update 1 file.

I tried re-uploading reset.zip to the S3 bucket with the updated template for example, but CodeBuild screamed that the YAML doesn't exist even though the path was correct and I even specified the version ID.

I'd be happy with any idea. Thanks

**Comment by moellr** [comment]
You should be able to update the reset.zip with your new AWS Nuke config without redeploying the whole app:
- download the reset.zip from the S3 bucket
- unzip it locally (e.g. into a test folder)
- update the Nuke config file
- zip all files in the folder to reset.zip (make sure you do not accidentally zip a path into your archive, run `unzip -l reset.zip` to confirm that all files have no folder prefix)
- upload back to S3 again
I have done that multiple times, should work ootb

**Comment by SheVyY** [comment]
@moellr  Thanks a lot

The problem was indeed in leaving paths in the zip archive as I zipped it via UI. Now I created a script for it, making sure no paths are left there, tested it and everything works.
