### ISSUE TITLE
aws-portal IAM policy update

### ISSUE THREAD

**Issue by gioc96** [awslabs/sandbox-accounts-for-events#42]
As reported in this [blog article](https://aws.amazon.com/it/blogs/aws-cloud-financial-management/changes-to-aws-billing-cost-management-and-account-consoles-permissions/):  AWS are retiring _aws-portal_ actions in IAM policy.

An update of [principal_policy.tmpl](https://github.com/awslabs/sandbox-accounts-for-events/blob/main/dce-integration/modules/fixtures/policies/principal_policy.tmpl) should be necessary.

In depht:
  ```
"Sid": "DenyCUR",
        "Effect": "Deny",
        "Action": [
          "aws-portal:ViewBilling",
          "aws-portal:ViewAccount",
          "ce:*",
          "cur:*"
        ],
        "Resource": "*"
      }
```

should be changed with mapped policy as reported [here](https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/migrate-granularaccess-iam-mapping-reference.html#mapping-for-aws-portalviewaccount) and [here](https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/migrate-granularaccess-iam-mapping-reference.html#mapping-for-aws-portalviewbilling).

Hope this can be useful.

**Comment by moellr** [comment]
Code has just been updated in the latest (today's) commit. Thx for flagging this change.
