### ISSUE TITLE
Error to list users with admin permission

### ISSUE THREAD

**Issue by eduardomartinsdarede** [awslabs/sandbox-accounts-for-events#45]
I can't list users after deploy, I think is something in cognito because I can ADD and Remove new users...

![image](https://github.com/awslabs/sandbox-accounts-for-events/assets/133807555/fcbabcf7-1a82-457d-b8b1-c49076774adb)

Error:

![image](https://github.com/awslabs/sandbox-accounts-for-events/assets/133807555/b659ed06-5dae-43a9-bfad-25119abb910f)

**Comment by eduardomartinsdarede** [comment]
More infos:

![image](https://github.com/awslabs/sandbox-accounts-for-events/assets/133807555/0b44e4a9-e289-4fce-93c0-f8263c28685b)

**Comment by eduardomartinsdarede** [comment]
@moellr the quickfix who worked is it:

https://github.com/aws-amplify/amplify-cli/compare/dev...marcomilon:amplify-cli:category-auth/fix-limit-not-converted-to-number

**Comment by philippegabert** [comment]
Hi there, 

when will this be implemented in this code/repo? How to update an existing installation with the bug fix? (And not having to change the lambda manually)

Thanks

**Comment by moellr** [comment]
Implemented now with the latest commit, feel free to merge with your local repo.

**Comment by krishnarastogi** [comment]
@moellr @eduardomartinsdarede 
I am still experiencing the same issue. Could you please share how you solved it?

**Comment by moellr** [comment]
Did you perform a reinstall of the whole project with the latest changes? That should fix it.
Alternatively you could manually apply these changes to your existing install: https://github.com/awslabs/sandbox-accounts-for-events/commit/a4e3a0a341c590e8c89fa969d5a3843e3e85b7d3 as a hotfix.
