### ISSUE TITLE
[Feature Request] Get temporary credentials to access the AWS account through CLI

### ISSUE THREAD

**Issue by philippegabert** [awslabs/sandbox-accounts-for-events#46]
Hi, 

A very important feature IMO is, for the users, to be able to get temporary credentials that they could use in their Terminal so they can use the CLI, etc.

The idea would be, on top of the access to the AWS console, to show a screen that display:
- Access key
- Secret Access Key
- Session token

Thanks

Philippe

**Comment by moellr** [comment]
Great idea, the backend is already prepared to provide this data. I will add this to my list for new features for Q1/2024.

**Comment by moellr** [comment]
Feature is now implemented with today's commit: The AWS account login popup now has an expandable section that displays AWS CLI credentials plus a copy-to-clipboard button.
Thanks for raising the idea, much appreciated.
