### ISSUE TITLE
[Feature Request] Pre-lease of accounts for an event / Installation of resources in pre-leased accounts

### ISSUE THREAD

**Issue by philippegabert** [awslabs/sandbox-accounts-for-events#47]
Hi, 

For some events, we may want to install resources on the accounts (ie: Deployment of Cloud Formation templates). It'd be great to be able to pre-lease accounts for an event (let's say 10) and to be able to interact with them before the event is started and/or the account is leased. 
Currently, to lease an account, you need to provide an e-mail address so you cannot really pre-lease accounts.
Also, it would be good to add a new status (in addition to Ready, NotReady and Leased) to indicate that pre-installation of resources is happening. 

Thanks

Philippe

**Comment by moellr** [comment]
Nice feature indeed, but out of scope for this small project (providing empty test accounts), as this would imply significant additional functionality behind the scenes. 
If you feel motivated, do not hesitate to develop this additional feature yourself and submit a pull request for it.
