### ISSUE TITLE
[Feature Request] Auto Start events

### ISSUE THREAD

**Issue by philippegabert** [awslabs/sandbox-accounts-for-events#48]
Hi, 

When creating an event, the admin needs to define the start date/time of the event. But this seems to be "for information only" (Unless I am mistaken). 
It would be great if there was an option to automatically start the event.

Thanks

**Comment by moellr** [comment]
Correct, the date/time information is for information only. Currently there is no mechanism for automated lifecycle events - I will need to investigate how much of a quick win this could be - but likely not a short-term feature.

**Comment by moellr** [comment]
Will not implement, this would extend the current scope of the project too far
