### ISSUE TITLE
Amplify build settings causing failure

### ISSUE THREAD

**Issue by emmarrig** [awslabs/sandbox-accounts-for-events#52]
Deploying a fresh Sandbox for Events. 

The Amplify app was failing to build due to "amazon-linux-extras" missing in the image, doing some digging it was Amazon Linux 2023's problem, the default image for the Amplify build image was Amazon Linux:2023. Solution changing this in Amplify under 'App Settings', 'Build settings', 'Build image settings' to 'Amazon Linux:2', resolved the problem and it was able to build successfully.

**Comment by moellr** [comment]
Fixed with today's commit, Amplify project is now safely build with Amazon Linux 2023
