### ISSUE TITLE
Average statistics zero balance when credits are available

### ISSUE THREAD

**Issue by geralexgr** [awslabs/sandbox-accounts-for-events#61]
When there are credits available on the account the reporting tab in the Average statistics is not displaying correct values.
 
<img width="432" alt="Screenshot 2024-07-19 at 11 22 26 AM" src="https://github.com/user-attachments/assets/2a5ce625-61a4-43b1-bbb8-666240f77499">

This issue seems to be created because the default filtering in cost explorer gets as default the credits. 

![Screenshot 2024-07-19 at 11 26 13 AM](https://github.com/user-attachments/assets/177b7510-0237-4b63-a013-e08a6c474eb7)

Is there any way we can fix the reporting tab? Can we somehow exclude credits from the reporting in the sandbox solution?

**Comment by moellr** [comment]
This project relies on the [DCE(TM)](https://github.com/Optum/dce) project  under the hood to handle account & lease assignments as well as tracking the AWS usage & consumption. As soon as the [DCE(TM)](https://github.com/Optum/dce) project supports your request, it also automatically apply to "Sandbox Account for Events".

It might be better to bring up your issue in the DCE(TM) project then.
