### ISSUE TITLE
bug: cannot setup master account due to EOL of AWS CodeCommit

### ISSUE THREAD

**Issue by mavogel** [awslabs/sandbox-accounts-for-events#62]
Due to the error `CreateRepository request is not allowed because there is no existing repository in this AWS account or AWS Organization` 

> Beginning on 06 June 2024, AWS CodeCommit ceased onboarding new customers. Going forward, only customers who have an existing repository in AWS CodeCommit will be able to create additional repositories.

See explanation: https://repost.aws/questions/QUshILm0xbTjWJZSD8afYVgA/codecommit-cannot-create-a-repository

Solution: 
1. request codecommit repository via support request
2. move away from codecommit to another VCS provider and change the resource
```yaml
AppUiAmplifyRepository:
    Type: AWS::CodeCommit::Repository
```

**Comment by diranetafen** [comment]
face the same issue, i used github as workaround

**Comment by mavogel** [comment]
great! Could you provider a PR with the instruction and cfn template updates how you made it work? That would be great

**Comment by moellr** [comment]
Issue is resolved now with latest commit (complete removal of CodeCommit, the build process is now run via CodeBuild instead of Amplify CI/CD)
