### ISSUE TITLE
[Makefile:43: build] Error 127

### ISSUE THREAD

**Issue by abilash44** [awslabs/sandbox-accounts-for-events#80]
Hi
I am getting this error when I follow the commands provided

![image](https://github.com/user-attachments/assets/2147504c-75c3-4756-ad14-469fc65dfe96)

Any idea what is wrong or how to fix this?

**Comment by moellr** [comment]
Just tested it, works well on my end.
I recommend looking at the Makefile and execute the commands in the section "build" manually in your terminal to find out which one of them failed. Perhaps your user does not have the permission to create folders or files in /mnt/c, or the zip command failed executing.

**Comment by abilash44** [comment]
That worked. I was running of a new machine for WSL and zip was not installed. 
Thank you for the help.
