### ISSUE TITLE
Add a separate account lease time for long events

### ISSUE THREAD

**Issue by svenfinke** [awslabs/sandbox-accounts-for-events#9]
I'd like to be able to create long running events, but keep the accounts lease time shorter (e.g. for Sandbox Self-Service Accounts for developers, where the event run's for multiple month but the lease should expire after 14 days)

**Comment by moellr** [comment]
You can currently achieve this by creating an event with a long duration (e.g. 90d), let the user lease an account in this event and afterwards manually edit their lease record with an updated, shortened expiry timestamp (e.g. 14d).
But generally speaking I like your idea. Will add it to my feature request list for further improvements & add-ons.

**Comment by moellr** [comment]
Will not implement, this would extend the current scope of the project too far
